version: '3.8'

services:

    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ../src:/var/www
            - ../nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db
            - rabbitmq3
            - redis


    db:
       image : mysql
       container_name : mysql
       volumes:
         - ../mysql/data:/var/lib/mysql
       ports:
         - "3306:3306"
       environment:
         MYSQL_DATABASE: ${DB_DATABASE}
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}



    app:
        container_name: drcase
        build:
            context: ../php
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www
    


    phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: phpmyadmin
       ports:
         - "3400:80"
       depends_on:
         - db

    redis:
        image: redis:6.2.1-alpine
        container_name: myredis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        volumes:
            - "./redis:/data"




    rabbitmq3:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq3'
        command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq


