version: '3.8'

services:

    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ../src:/var/www
            - ../nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db


    db:
       image : mysql
       container_name : mysql
       volumes:
         - ../mysql/data:/var/lib/mysql
       ports:
         - "3306:3306"
       environment:
         MYSQL_DATABASE: dr
         MYSQL_ROOT_PASSWORD: password



    app:
        container_name: drcase
        build:
            context: ../php
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www


    phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: phpmyadmin
       ports:
         - "3400:80"
       depends_on:
         - db

    redis:
        image: redis:6.2.1-alpine
        container_name: myredis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        volumes:
            - "./redis:/data"
